Index sale 3
SetProtocol/index-deployments pull request #87
Opened 2021-09-30 00:19 UTC by 0xModene

2021-09-30 16:46 UTC, controtie commented
Circle CI is failing, looks like you're not using the checksummed address in the test.

2021-09-30 20:44 UTC, ncitron requested changes
Other than this one problem noted above everything else looks good.

2021-09-30 20:44 UTC, ncitron commented on deployments/constants/025_index_sale_3.ts
> +    address: "0x7E2E80E8250844Dd4E558f13850380D5af8F0C61",
Is this the second time blockchain.com ventures has invested with us? Looking at https://github.com/SetProtocol/index-deployments/blob/master/deployments/outputs/1-production.json#L55 it looks like they were involved in round 2.

Was this a mistake or are they actually investing with us a second time?

If it was not a mistake, we need to change up how we are naming the contracts for this round (or get them to use a new address). This is because our deployments will skip them since there has already been an OtcEscrow contract deployed with the name "OtcEscrow - 0x7E2E80E8250844Dd4E558f13850380D5af8F0C61"

2021-09-30 20:45 UTC, ncitron commented on deployments/constants/025_index_sale_3.ts
> +    address: "0x7E2E80E8250844Dd4E558f13850380D5af8F0C61",
This is also why CircleCI is failing

2021-10-01 04:05 UTC, ncitron approved these changes
LGTM

2021-10-01 19:11 UTC, controtie approved these changes
LGTM

2021-10-01 19:12 UTC, merged